### ISSUE TITLE
Does not work for multiple tabs

### ISSUE THREAD

**Issue by rounaksamdadia** [Fomtriok/sessionExpiration.js#4]
Hi,
I tried the demo and it does not work for multiple tabs. Every tab runs its own independent timer and JS. Can you check it out once? I just tried the demo you have put in. Did not implement on my project yet.

**Comment by Fomtriok** [comment]
Thank you for your input Rounak.

I assume you mean "all tabs don't get redirected to the logoutUrl". I have now changed that per your request. Before it did however track the time on all tabs, stopping logout if any tab saw interaction and then restarting the timer when reaching zero, but your input makes sense, so now it works like you suggested:

* All tabs now get redirected to logoutUrl upon timer expiration, to ensure logout.
* Also, the timer gets synched across tabs now, as soon as one interacts with any tab. Sometimes there is a difference of one or two seconds between tabs for some reason - but since it is such a small bug I leave it for now.

Best, Fomtriok
